### ISSUE TITLE
duplicate team listings

### ISSUE THREAD

**Issue by 1fish2** [the-blue-alliance/the-blue-alliance-android#511]
Version 3.0.0 (presumably a beta release).

Steps to reproduce:
- Search for `spartan`. (Or search for `robotics` or another term that's in many team names.)
- Tap the "23 MORE" button.

Result:
- A list of `Teams matching "spartan"` with each entry listed twice.

Duplicate listings don't occur if you search for `regional` even though there are many events that match the query.

**Comment by phil-lopreiato** [comment]
I think this has been fixed in master (https://github.com/the-blue-alliance/the-blue-alliance-android/commit/3939fbe38ec93538840a91f401662ca97bc6aa8b) since that release was pushed. Can you verify that @1fish2?

**Comment by 1fish2** [comment]
Happily, running a debug build of the code in master does not have this bug.
But is that because it started afresh fetching data, because of the code changes, both, or either?

I went to Settings > The Blue Alliance (not The Blue Alliance Debug) > Storage > CLEAR DATA, then retried the steps to repro. --> No duplicate entries now.

How to verify the fix?

**Comment by nwalters512** [comment]
Best way to verify is probably to uninstall the app, install an old version, then install the latest version and let the upgrade procedures run. That'll tell us if it's a problem with upgrading

Of course, an easy "fix" would simply be to modify the SQL queries for search to only return distinct rows, so even if duplicates are somehow inserted, the user doesn't see them.

**Comment by 1fish2** [comment]
That sounds good: Uninstall the debug build, then run at a suitable old commit, then build and run at the current 3.0.0 beta commit, reproduce the bug, then update to master and verify the fix.

Can anyone give two suitable commit IDs?

I like the SQL SELECT DISTINCT idea, too.

**Comment by phil-lopreiato** [comment]
I think the commit I linked above is a good bisect point. I'm pretty sure this was fixed on that one, which caused the search indexes to be removed on the next data download. So I think the answer is both

**Comment by 1fish2** [comment]
I tried to verify the fix by running at 3939fbe^ and a few preceding commits, and then at 3939fbe, but the code throws NPE while fetching the initial data. The current master works fine, so let's stick with "closed."

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
    at com.thebluealliance.androidclient.datafeed.maps.AddDistrictKeys.call(AddDistrictKeys.java:23)
    at com.thebluealliance.androidclient.datafeed.maps.AddDistrictKeys.call(AddDistrictKeys.java:13)
    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap.lambda$mapAndWriteResponseBody$27(RetrofitResponseMap.java:110)
    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap.access$lambda$2(RetrofitResponseMap.java)
    at com.thebluealliance.androidclient.datafeed.maps.RetrofitResponseMap$$Lambda$4.call(Unknown Source)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
    at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe$2.onResponse(RxJavaCallAdapterFactory.java:109)
    at retrofit.OkHttpCall$1.callSuccess(OkHttpCall.java:77)
    at retrofit.OkHttpCall$1.onResponse(OkHttpCall.java:95)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: retrofit.Response.class
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
   ... 8 more
```

**Comment by 1fish2** [comment]
This bug is still present on an Android tablet.

Perhaps the app still needs to delete duplicate rows or use `SELECT DISTINCT` to cope.

**Comment by phil-lopreiato** [comment]
Shoot. 

`SELECT DISTINCT` sounds like a good idea. (as well as hunting down the root cause, probably while updating/adding new search indexes)
